name: build-and-test

on:
  pull_request:
    branches: 
      - develop
  push:
    branches:
      - develop

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: coderrect/openrace-env

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          conan install ..
          cmake -DLLVM_BUILD_TYPE=$BUILD_TYPE -DLLVM_DIR=/usr/local/lib/cmake/llvm/ .. 
          cmake --build . -j
      
      - name: Test
        run: |
          cd build
          ctest
